# Generated by Django 6.0 on 2025-12-08 13:13

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, default='Nepal', max_length=15, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=6)),
                ('profile_image', models.ImageField(blank=True, default='users/default_user.png', null=True, upload_to=users.models.Profile.generateImagePath)),
                ('dob', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('jobseeker', 'Job Seeker'), ('recruiter', 'Recruiter')], default='jobseeker', max_length=10)),
                ('skills', models.TextField(help_text='Comma separated skills')),
                ('experience', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('preferred_location', models.CharField(blank=True, max_length=100)),
                ('preferred_job_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
