# Generated by Django 6.0 on 2025-12-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('users', '0004_alter_profile_address_alter_profile_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='skills.skill'),
        ),
    ]
