# Generated by Django 6.0 on 2026-01-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
