# Generated by Django 6.0 on 2026-02-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_work_mode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
