# Generated by Django 6.0 on 2026-02-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_preferred_work_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_work_mode',
            field=models.CharField(blank=True, choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=20),
        ),
    ]
