# Generated by Django 6.0 on 2026-02-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_preferred_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_job_type',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_work_mode',
            field=models.CharField(blank=True, choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=20),
        ),
    ]
