# Generated by Django 6.0 on 2026-02-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_preferred_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Job Seeker', 'Job Seeker'), ('Recruiter', 'Recruiter')], default='Job Seeker', max_length=10),
        ),
    ]
