# Generated by Django 6.0 on 2026-03-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='search_vector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
