# Generated by Django 6.0 on 2025-12-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_recruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='posted_by',
        ),
    ]
