# Generated by Django 6.0 on 2025-12-25 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_is_verified'),
        ('jobs', '0003_remove_job_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company'),
            preserve_default=False,
        ),
    ]
