# Generated by Django 6.0 on 2026-03-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_employment_type_alter_job_work_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='search_vector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
