# Generated by Django 6.0 on 2025-12-25 05:03

import companies.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('public_url', models.SlugField(unique=True)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(max_length=100)),
                ('organization_size', models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1000+', '1000+ employees')], max_length=20)),
                ('organization_type', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('non_profit', 'Non-profit'), ('government', 'Government'), ('educational', 'Educational'), ('self_employed', 'Self-employed')], max_length=20)),
                ('logo', models.ImageField(default='users/default_company.png', upload_to=companies.models.Company.generateImagePath)),
                ('tagline', models.CharField(blank=True, max_length=120)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
