# Generated by Django 6.0 on 2025-12-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_verified',
        ),
    ]
