# Generated by Django 6.0 on 2026-03-14 07:37

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='companies/default_company.png', upload_to=companies.models.Company.generateImagePath),
        ),
    ]
