# Generated by Django 6.0 on 2026-02-21 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntf_id', models.CharField(choices=[('ACCOUNT_CREATED', 'NTF-001'), ('EMAIL_VERIFIED', 'NTF-002'), ('LOGIN_SUCCESS', 'NTF-003'), ('LOGIN_NEW_DEVICE', 'NTF-004'), ('OTP_SENT', 'NTF-005'), ('PASSWORD_RESET', 'NTF-006'), ('ACCOUNT_LOCKED', 'NTF-007'), ('POLICY_UPDATED', 'NTF-008'), ('PASSWORD_CHANGED', 'NTF-009'), ('LOGIN_ATTEMPT', 'NTF-010'), ('TWO_FA_ENABLED', 'NTF-011'), ('TWO_FA_DISABLED', 'NTF-012'), ('OTP_REGISTER', 'OTP-001'), ('OTP_EMAIL_CHANGE', 'OTP-002'), ('OTP_PASSWORD_RESET', 'OTP-003'), ('OTP_USERNAME_RESET', 'OTP-004'), ('OTP_LOGIN', 'OTP-005')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('critical', 'Critical'), ('action', 'Action Required'), ('session', 'Session'), ('payment', 'Payment'), ('message', 'Message'), ('match', 'Match'), ('achievement', 'Achievement')], default='info', max_length=20)),
                ('notify_client', models.BooleanField(default=False)),
                ('notify_educator', models.BooleanField(default=False)),
                ('notify_admin', models.BooleanField(default=False)),
                ('send_in_app', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=False)),
                ('show_in_recent', models.BooleanField(default=True, help_text='Green in Excel = True, others = False', verbose_name='Show in Recent Activity / Bell Dropdown')),
                ('in_app_message', models.TextField(help_text='e.g. {{ actor }} requested a session at {{ session_time }}')),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('email_html', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntf_id', models.CharField(choices=[('ACCOUNT_CREATED', 'NTF-001'), ('EMAIL_VERIFIED', 'NTF-002'), ('LOGIN_SUCCESS', 'NTF-003'), ('LOGIN_NEW_DEVICE', 'NTF-004'), ('OTP_SENT', 'NTF-005'), ('PASSWORD_RESET', 'NTF-006'), ('ACCOUNT_LOCKED', 'NTF-007'), ('POLICY_UPDATED', 'NTF-008'), ('PASSWORD_CHANGED', 'NTF-009'), ('LOGIN_ATTEMPT', 'NTF-010'), ('TWO_FA_ENABLED', 'NTF-011'), ('TWO_FA_DISABLED', 'NTF-012'), ('OTP_REGISTER', 'OTP-001'), ('OTP_EMAIL_CHANGE', 'OTP-002'), ('OTP_PASSWORD_RESET', 'OTP-003'), ('OTP_USERNAME_RESET', 'OTP-004'), ('OTP_LOGIN', 'OTP-005')], max_length=50)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('critical', 'Critical'), ('action', 'Action Required'), ('session', 'Session'), ('payment', 'Payment'), ('message', 'Message'), ('match', 'Match'), ('achievement', 'Achievement')], max_length=20)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_f42485_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('otp_type', models.CharField(choices=[('register', 'Register'), ('email_change', 'Email Change'), ('password_reset', 'Password Reset'), ('username_reset', 'Username Reset'), ('login', 'Login')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_used', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'otp_type'], name='notificatio_user_id_5562bb_idx'), models.Index(fields=['code', 'otp_type'], name='notificatio_code_4816f9_idx')],
            },
        ),
    ]
