# Generated by Django 6.0 on 2026-02-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='notify_client',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='notify_educator',
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='notify_employer',
            field=models.BooleanField(default=False, verbose_name='Notify Employer'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='notify_jobseeker',
            field=models.BooleanField(default=False, verbose_name='Notify JobSeeker'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='ntf_id',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'NTF-001'), ('EMAIL_VERIFIED', 'NTF-002'), ('LOGIN_SUCCESS', 'NTF-003'), ('LOGIN_NEW_DEVICE', 'NTF-004'), ('OTP_SENT', 'NTF-005'), ('PASSWORD_RESET', 'NTF-006'), ('ACCOUNT_LOCKED', 'NTF-007'), ('POLICY_UPDATED', 'NTF-008'), ('PASSWORD_CHANGED', 'NTF-009'), ('LOGIN_ATTEMPT', 'NTF-010'), ('TWO_FA_ENABLED', 'NTF-011'), ('TWO_FA_DISABLED', 'NTF-012'), ('OTP_REGISTER', 'OTP-001'), ('OTP_EMAIL_CHANGE', 'OTP-002'), ('OTP_PASSWORD_RESET', 'OTP-003'), ('OTP_USERNAME_RESET', 'OTP-004'), ('OTP_LOGIN', 'OTP-005'), ('JOB_APPLICATION_RECEIVED', 'NTF-101'), ('APPLICATION_STATUS_CHANGED', 'NTF-102')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='ntf_id',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'NTF-001'), ('EMAIL_VERIFIED', 'NTF-002'), ('LOGIN_SUCCESS', 'NTF-003'), ('LOGIN_NEW_DEVICE', 'NTF-004'), ('OTP_SENT', 'NTF-005'), ('PASSWORD_RESET', 'NTF-006'), ('ACCOUNT_LOCKED', 'NTF-007'), ('POLICY_UPDATED', 'NTF-008'), ('PASSWORD_CHANGED', 'NTF-009'), ('LOGIN_ATTEMPT', 'NTF-010'), ('TWO_FA_ENABLED', 'NTF-011'), ('TWO_FA_DISABLED', 'NTF-012'), ('OTP_REGISTER', 'OTP-001'), ('OTP_EMAIL_CHANGE', 'OTP-002'), ('OTP_PASSWORD_RESET', 'OTP-003'), ('OTP_USERNAME_RESET', 'OTP-004'), ('OTP_LOGIN', 'OTP-005'), ('JOB_APPLICATION_RECEIVED', 'NTF-101'), ('APPLICATION_STATUS_CHANGED', 'NTF-102')], max_length=50),
        ),
    ]
