# Generated by Django 6.0 on 2026-02-21 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notificationtemplate_notify_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='template',
        ),
        migrations.RemoveIndex(
            model_name='verificationcode',
            name='notificatio_user_id_5562bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='verificationcode',
            name='notificatio_code_4816f9_idx',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='action_url',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='ntf_id',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='target_ct',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='type',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('Info', 'Info'), ('Success', 'Success'), ('Warning', 'Warning'), ('Error', 'Error')], default='Info', max_length=20),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='purpose',
            field=models.CharField(choices=[('Register', 'Register'), ('Login', 'Login'), ('Change Password', 'Change Password'), ('Change Email', 'Change Email')], default='Register', max_length=20),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['user', 'purpose'], name='notificatio_user_id_5ff5de_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['code', 'purpose'], name='notificatio_code_d509b2_idx'),
        ),
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
        migrations.RemoveField(
            model_name='verificationcode',
            name='email',
        ),
        migrations.RemoveField(
            model_name='verificationcode',
            name='otp_type',
        ),
    ]
